/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ittimfn.same;

import ittimfn.same.controller.Controller;

public class App {
    public void exec(String[] args) {
        for(int i = 0 ; i < 5 ; i++) {
            new Controller().exec(Integer.toString(i));
        }
    }

    public static void main(String[] args) {
        new App().exec(args);
    }
}
